<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
	  <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	  <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <OutputType>Library</OutputType>
    <Configurations>Debug;Release</Configurations>
    <OutputPath>..\..\build\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="SAM.Core">
      <HintPath>..\..\..\SAM\build\SAM.Core.dll</HintPath>
    </Reference>
    <Reference Include="SAM.Weather">
      <HintPath>..\..\..\SAM\build\SAM.Weather.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SAM.Core.UI\SAM.Core.UI.csproj" />
  </ItemGroup>
</Project>